### ISSUE TITLE
네비게이션바

### ISSUE THREAD

**Issue by ghost** [SoftWareAndGuider/Communication#2]
**학교 컴퓨터실** 기준으로 
![캡처](https://user-images.githubusercontent.com/42382793/89141160-ab044200-d57e-11ea-9913-036d90d18838.PNG)
이런 식으로 나오게 되는데, 이 점을 해결하기 위해서 학교 마크만 있는 파일을 새로 하나 저장(정사각형 사이즈)해서 넣는 것이 좋을 것 같다고 생각됨

**Comment by pmh-only** [comment]
반영하도록 하겠습니다

의견 감사합니다

**Comment by pmh-only** [comment]
@seomingyu11 
커밋 [f12dd4a](https://github.com/SoftWareAndGuider/Communication/commit/f12dd4ac1279f8bfc644926c140101fd97d04fb9)에서 해결하였습니다

로고를 새로 제작 하는 대신 부모 원소의 맞추어지도록 하였습니다
https://github.com/SoftWareAndGuider/Communication/blob/f12dd4ac1279f8bfc644926c140101fd97d04fb9/src/main.css#L5-L7
