### ISSUE TITLE
매우 심상치 않은 것

### ISSUE THREAD

**Issue by Helloyunho** [SoftWareAndGuider/Communication#4]
https://github.com/SoftWareAndGuider/Communication/blob/9d533c07a1e4ed821e0af98f19ad7ba592e9dabf/database.sql#L64

관리자 비밀번호가 SQL에 나와도 괜찮은건가요

**Comment by pmh-only** [comment]
네, 솔트 엄청 뿌린겁니다

**Comment by pmh-only** [comment]
아니 글고 그건 셈플이잖아

**Comment by Helloyunho** [comment]
아 그러면 지금은 비번 바꿈? ㄲㅂ

**Comment by pmh-only** [comment]
안바꿨겠ㄴ...
